import { sql } from "drizzle-orm";
import { db, pool } from "@/db";
import { categories, products } from "@/db/schema";
import { SEED_CATEGORIES, SEED_PRODUCTS } from "./seed-data";
import { pexels } from "./utils";

/**
 * Exact DDL generated by `drizzle-kit export` for src/db/schema.ts.
 * Only executed when the tables are missing (e.g. a brand-new database),
 * so it never conflicts with `drizzle-kit push`.
 */
const DDL = `
CREATE TABLE IF NOT EXISTS "users" ("id" serial PRIMARY KEY NOT NULL, "name" text NOT NULL, "email" text NOT NULL, "password_hash" text NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "users_email_unique" UNIQUE("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" text PRIMARY KEY NOT NULL, "user_id" integer NOT NULL, "expires_at" timestamp with time zone NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "categories" ("id" serial PRIMARY KEY NOT NULL, "slug" text NOT NULL, "name" text NOT NULL, "tagline" text DEFAULT '' NOT NULL, "description" text DEFAULT '' NOT NULL, "image" text DEFAULT '' NOT NULL, "sort_order" integer DEFAULT 0 NOT NULL, CONSTRAINT "categories_slug_unique" UNIQUE("slug"));
CREATE TABLE IF NOT EXISTS "products" ("id" serial PRIMARY KEY NOT NULL, "slug" text NOT NULL, "name" text NOT NULL, "brand" text DEFAULT '' NOT NULL, "short_description" text DEFAULT '' NOT NULL, "description" text DEFAULT '' NOT NULL, "category_id" integer NOT NULL, "price_cents" integer NOT NULL, "compare_at_cents" integer, "images" jsonb DEFAULT '[]'::jsonb NOT NULL, "features" jsonb DEFAULT '[]'::jsonb NOT NULL, "specs" jsonb DEFAULT '[]'::jsonb NOT NULL, "rating" real DEFAULT 0 NOT NULL, "review_count" integer DEFAULT 0 NOT NULL, "stock" integer DEFAULT 0 NOT NULL, "is_featured" boolean DEFAULT false NOT NULL, "is_new" boolean DEFAULT false NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "products_slug_unique" UNIQUE("slug"));
CREATE TABLE IF NOT EXISTS "cart_items" ("id" serial PRIMARY KEY NOT NULL, "owner_key" text NOT NULL, "product_id" integer NOT NULL, "quantity" integer DEFAULT 1 NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "wishlist_items" ("id" serial PRIMARY KEY NOT NULL, "owner_key" text NOT NULL, "product_id" integer NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE IF NOT EXISTS "orders" ("id" serial PRIMARY KEY NOT NULL, "order_number" text NOT NULL, "user_id" integer NOT NULL, "status" text DEFAULT 'processing' NOT NULL, "subtotal_cents" integer NOT NULL, "shipping_cents" integer NOT NULL, "total_cents" integer NOT NULL, "delivery_method" text NOT NULL, "payment_method" text NOT NULL, "full_name" text NOT NULL, "email" text NOT NULL, "phone" text NOT NULL, "address" text NOT NULL, "city" text NOT NULL, "postal_code" text NOT NULL, "country" text NOT NULL, "notes" text DEFAULT '' NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "orders_order_number_unique" UNIQUE("order_number"));
CREATE TABLE IF NOT EXISTS "order_items" ("id" serial PRIMARY KEY NOT NULL, "order_id" integer NOT NULL, "product_id" integer, "product_name" text NOT NULL, "product_slug" text NOT NULL, "image" text DEFAULT '' NOT NULL, "unit_price_cents" integer NOT NULL, "quantity" integer NOT NULL);
CREATE TABLE IF NOT EXISTS "newsletter_subscribers" ("id" serial PRIMARY KEY NOT NULL, "email" text NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "newsletter_subscribers_email_unique" UNIQUE("email"));
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "products" ADD CONSTRAINT "products_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE restrict ON UPDATE no action;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "wishlist_items" ADD CONSTRAINT "wishlist_items_product_id_products_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
CREATE UNIQUE INDEX IF NOT EXISTS "cart_items_owner_product_uq" ON "cart_items" USING btree ("owner_key","product_id");
CREATE INDEX IF NOT EXISTS "order_items_order_idx" ON "order_items" USING btree ("order_id");
CREATE INDEX IF NOT EXISTS "orders_user_idx" ON "orders" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "products_category_idx" ON "products" USING btree ("category_id");
CREATE INDEX IF NOT EXISTS "sessions_user_idx" ON "sessions" USING btree ("user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "wishlist_items_owner_product_uq" ON "wishlist_items" USING btree ("owner_key","product_id");
`;

const ALREADY_EXISTS_CODES = new Set(["42P07", "42710", "42P16", "23505"]);

let readyPromise: Promise<void> | null = null;

/** Ensures tables exist and the catalog is seeded. Memoized per server process. */
export function ensureDb(): Promise<void> {
  if (!readyPromise) {
    readyPromise = bootstrap().catch((error) => {
      readyPromise = null;
      throw error;
    });
  }
  return readyPromise;
}

async function ensureTables() {
  const { rows } = await pool.query<{ t: string | null }>(
    "select to_regclass('public.products')::text as t",
  );
  if (rows[0]?.t) return;

  const statements = DDL.split(";\n")
    .map((s) => s.trim())
    .filter(Boolean);
  for (const statement of statements) {
    try {
      await pool.query(statement);
    } catch (error) {
      const code = (error as { code?: string }).code;
      if (!code || !ALREADY_EXISTS_CODES.has(code)) throw error;
    }
  }
}

async function bootstrap() {
  await ensureTables();

  const [{ count }] = await db
    .select({ count: sql<number>`cast(count(*) as int)` })
    .from(categories);
  if (count > 0) return;

  await db.transaction(async (tx) => {
    // Serialize concurrent seeders (multiple workers starting at once).
    await tx.execute(sql`select pg_advisory_xact_lock(771204)`);
    const [{ again }] = await tx
      .select({ again: sql<number>`cast(count(*) as int)` })
      .from(categories);
    if (again > 0) return;

    await tx.insert(categories).values(SEED_CATEGORIES).onConflictDoNothing();
    const rows = await tx.select({ id: categories.id, slug: categories.slug }).from(categories);
    const categoryIds = new Map(rows.map((r) => [r.slug, r.id]));

    const now = Date.now();
    const day = 24 * 60 * 60 * 1000;
    const values = SEED_PRODUCTS.flatMap((p, index) => {
      const categoryId = categoryIds.get(p.category);
      if (!categoryId) return [];
      return [
        {
          slug: p.slug,
          name: p.name,
          brand: p.brand,
          shortDescription: p.short,
          description: p.description,
          categoryId,
          priceCents: Math.round(p.price * 100),
          compareAtCents: p.compareAt ? Math.round(p.compareAt * 100) : null,
          images: p.images.map((id) => pexels(id)),
          features: p.features,
          specs: p.specs.map(([label, value]) => ({ label, value })),
          rating: p.rating,
          reviewCount: p.reviews,
          stock: p.stock,
          isFeatured: Boolean(p.featured),
          isNew: Boolean(p.isNew),
          createdAt: new Date(now - (p.isNew ? index % 7 : 20 + index) * day),
        },
      ];
    });
    await tx.insert(products).values(values).onConflictDoNothing();
  });
}
